In [1]:
%matplotlib inline

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

In [41]:

users = pd.read_csv("usersfull.csv", sep=",")

movies = pd.read_csv("procMovies1Hot.csv", sep=",")

ratings = pd.read_csv("ratings.csv", sep=",")


movies.columns

#movies.set_index('movieID')
#ratings.columns
#ratings.set_index('movieID')

Index(['Unnamed: 0', 'movieID', 'title', 'year', 'howManyGenres', 'Action',
       'Adventure', 'Animation', 'Children's', 'Comedy', 'Crime',
       'Documentary', 'Drama', 'Fantasy', 'Film-Noir', 'Horror', 'Musical',
       'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western'],
      dtype='object')

In [42]:
movies=movies.drop('Unnamed: 0',axis=1) # remove useless column

In [44]:
mr=pd.merge(ratings,movies,how='inner',on='movieID')
mr

,userID,movieID,rating,time,title,year,howManyGenres,Action,Adventure,Animation,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,1193,5,2000-12-31,One Flew Over the Cuckoo's Nest,1975,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,1193,5,2000-12-31,One Flew Over the Cuckoo's Nest,1975,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,12,1193,4,2000-12-31,One Flew Over the Cuckoo's Nest,1975,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,15,1193,4,2000-12-30,One Flew Over the Cuckoo's Nest,1975,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,17,1193,5,2000-12-30,One Flew Over the Cuckoo's Nest,1975,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,18,1193,4,2000-12-30,One Flew Over the Cuckoo's Nest,1975,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,19,1193,5,2001-02-21,One Flew Over the Cuckoo's Nest,1975,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,24,1193,5,2000-12-30,One Flew Over the Cuckoo's Nest,1975,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,28,1193,3,2000-12-29,One Flew Over the Cuckoo's Nest,1975,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,33,1193,5,2001-01-03,One Flew Over the Cuckoo's Nest,1975,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,39,1193,5,2000-12-28,One Flew Over the Cuckoo's Nest,1975,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,42,1193,3,2000-12-28,One Flew Over the Cuckoo's Nest,1975,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,44,1193,4,2000-12-28,One Flew Over the Cuckoo's Nest,1975,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,47,1193,4,2000-12-28,One Flew Over the Cuckoo's Nest,1975,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,48,1193,4,2000-12-28,One Flew Over the Cuckoo's Nest,1975,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,49,1193,4,2001-01-06,One Flew Over the Cuckoo's Nest,1975,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,53,1193,5,2000-12-27,One Flew Over the Cuckoo's Nest,1975,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,54,1193,5,2000-12-27,One Flew Over the Cuckoo's Nest,1975,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,58,1193,5,2000-12-27,One Flew Over the Cuckoo's Nest,1975,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,59,1193,4,2000-12-27,One Flew Over the Cuckoo's Nest,1975,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,62,1193,4,2000-12-28,One Flew Over the Cuckoo's Nest,1975,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,80,1193,4,2000-12-26,One Flew Over the Cuckoo's Nest,1975,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22,81,1193,5,2000-12-26,One Flew Over the Cuckoo's Nest,1975,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23,88,1193,5,2000-12-24,One Flew Over the Cuckoo's Nest,1975,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24,89,1193,5,2000-12-24,One Flew Over the Cuckoo's Nest,1975,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25,95,1193,5,2000-12-24,One Flew Over the Cuckoo's Nest,1975,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,96,1193,3,2000-12-24,One Flew Over the Cuckoo's Nest,1975,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27,99,1193,2,2001-02-21,One Flew Over the Cuckoo's Nest,1975,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28,102,1193,5,2002-12-24,One Flew Over the Cuckoo's Nest,1975,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,104,1193,2,2000-12-23,One Flew Over the Cuckoo's Nest,1975,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1000179,4933,3084,3,2000-07-05,Home Page,1999,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1000180,4802,2218,2,2002-02-28,Juno and Paycock,1930,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1000181,4812,2308,2,2000-07-07,Detroit 9000,1973,2,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1000182,4874,624,4,2000-07-05,Condition Red,1995,3,1,0,0,...,0,0,0,0,0,0,0,1,0,0
1000183,5059,1434,4,2000-07-01,"Stranger, The",1994,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1000184,5947,1434,4,2000-05-01,"Stranger, The",1994,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1000185,5077,1868,3,2000-07-01,"Truce, The",1996,2,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1000186,5944,1868,1,2000-05-01,"Truce, The",1996,2,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1000187,5105,404,3,2000-06-30,Brother Minister: The Assassination of Malcolm X,1994,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1000188,5185,404,4,2000-07-12,Brother Minister: The Assassination of Malcolm X,1994,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1000189,5532,404,5,2000-05-29,Brother Minister: The Assassination of Malcolm X,1994,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1000190,5543,404,3,2000-06-04,Brother Minister: The Assassination of Malcolm X,1994,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1000191,5220,2543,3,2000-06-21,Six Ways to Sunday,1997,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1000192,5754,2543,4,2000-05-14,Six Ways to Sunday,1997,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1000193,5227,591,3,2000-06-20,Tough and Deadly,1995,3,1,0,0,...,0,0,0,0,0,0,0,1,0,0
1000194,5795,591,1,2000-05-12,Tough and Deadly,1995,3,1,0,0,...,0,0,0,0,0,0,0,1,0,0
1000195,5313,3656,5,2000-06-13,Lured,1947,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1000196,5328,2438,4,2000-06-12,Outside Ozona,1998,2,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1000197,5334,3323,3,2000-06-12,Chain of Fools,2000,2,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1000198,5334,127,1,2000-06-12,"Silence of the Palace, The (Saimt el Qusur)",1994,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1000199,5334,3382,5,2000-06-12,Song of Freedom,1936,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1000200,5420,1843,3,2000-06-05,Slappy and the Stinkers,1998,2,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1000201,5433,286,3,2000-06-05,Nemesis 2: Nebula,1995,3,1,0,0,...,0,0,0,0,0,0,1,1,0,0
1000202,5494,3530,4,2000-06-01,Smoking/No Smoking,1993,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1000203,5556,2198,3,2000-05-27,Modulations,1998,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1000204,5949,2198,5,2000-05-20,Modulations,1998,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1000205,5675,2703,3,2000-12-05,Broken Vessels,1998,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1000206,5780,2845,1,2000-05-12,White Boys,1999,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1000207,5851,3607,5,2000-05-08,One Little Indian,1973,3,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1000208,5938,2909,4,2000-05-02,"Five Wives, Three Secretaries and Me",1998,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [46]:
mr.isnull().sum()

userID           0
movieID          0
rating           0
time             0
title            0
year             0
howManyGenres    0
Action           0
Adventure        0
Animation        0
Children's       0
Comedy           0
Crime            0
Documentary      0
Drama            0
Fantasy          0
Film-Noir        0
Horror           0
Musical          0
Mystery          0
Romance          0
Sci-Fi           0
Thriller         0
War              0
Western          0
dtype: int64

In [47]:
urm=pd.merge(mr,users,how='inner',on='userID')
urm.shape

(989862, 34)

In [48]:
urm.head()
urm.sort_values(['userID','time'])

,userID,movieID,rating,time,title,year,howManyGenres,Action,Adventure,Animation,...,Western,gender,age,occupation,zipCode,city,state,lat,long,country
0,1,1193,5,2000-12-31,One Flew Over the Cuckoo's Nest,1975,1,0,0,0,...,0,F,12.0,10,48067,ROYAL OAK,MI,42.50,-83.15,US
1,1,661,3,2000-12-31,James and the Giant Peach,1996,3,0,0,1,...,0,F,12.0,10,48067,ROYAL OAK,MI,42.50,-83.15,US
2,1,914,3,2000-12-31,My Fair Lady,1964,2,0,0,0,...,0,F,12.0,10,48067,ROYAL OAK,MI,42.50,-83.15,US
3,1,3408,4,2000-12-31,Erin Brockovich,2000,1,0,0,0,...,0,F,12.0,10,48067,ROYAL OAK,MI,42.50,-83.15,US
5,1,1197,3,2000-12-31,"Princess Bride, The",1987,4,1,1,0,...,0,F,12.0,10,48067,ROYAL OAK,MI,42.50,-83.15,US
6,1,1287,5,2000-12-31,Ben-Hur,1959,3,1,1,0,...,0,F,12.0,10,48067,ROYAL OAK,MI,42.50,-83.15,US
7,1,2804,5,2000-12-31,"Christmas Story, A",1983,2,0,0,0,...,0,F,12.0,10,48067,ROYAL OAK,MI,42.50,-83.15,US
8,1,594,4,2000-12-31,Snow White and the Seven Dwarfs,1937,3,0,0,1,...,0,F,12.0,10,48067,ROYAL OAK,MI,42.50,-83.15,US
9,1,919,4,2000-12-31,"Wizard of Oz, The",1939,4,0,1,0,...,0,F,12.0,10,48067,ROYAL OAK,MI,42.50,-83.15,US
11,1,938,4,2000-12-31,Gigi,1958,1,0,0,0,...,0,F,12.0,10,48067,ROYAL OAK,MI,42.50,-83.15,US
12,1,2398,4,2000-12-31,Miracle on 34th Street,1947,1,0,0,0,...,0,F,12.0,10,48067,ROYAL OAK,MI,42.50,-83.15,US
13,1,2918,4,2000-12-31,Ferris Bueller's Day Off,1986,1,0,0,0,...,0,F,12.0,10,48067,ROYAL OAK,MI,42.50,-83.15,US
14,1,1035,5,2000-12-31,"Sound of Music, The",1965,1,0,0,0,...,0,F,12.0,10,48067,ROYAL OAK,MI,42.50,-83.15,US
15,1,2791,4,2000-12-31,Airplane!,1980,1,0,0,0,...,0,F,12.0,10,48067,ROYAL OAK,MI,42.50,-83.15,US
17,1,2018,4,2000-12-31,Bambi,1942,2,0,0,1,...,0,F,12.0,10,48067,ROYAL OAK,MI,42.50,-83.15,US
18,1,3105,5,2000-12-31,Awakenings,1990,1,0,0,0,...,0,F,12.0,10,48067,ROYAL OAK,MI,42.50,-83.15,US
19,1,2797,4,2000-12-31,Big,1988,2,0,0,0,...,0,F,12.0,10,48067,ROYAL OAK,MI,42.50,-83.15,US
20,1,2321,3,2000-12-31,Pleasantville,1998,1,0,0,0,...,0,F,12.0,10,48067,ROYAL OAK,MI,42.50,-83.15,US
21,1,720,3,2000-12-31,Wallace & Gromit: The Best of Aardman Animation,1996,1,0,0,1,...,0,F,12.0,10,48067,ROYAL OAK,MI,42.50,-83.15,US
22,1,1270,5,2000-12-31,Back to the Future,1985,2,0,0,0,...,0,F,12.0,10,48067,ROYAL OAK,MI,42.50,-83.15,US
24,1,2340,3,2000-12-31,Meet Joe Black,1998,1,0,0,0,...,0,F,12.0,10,48067,ROYAL OAK,MI,42.50,-83.15,US
26,1,1097,4,2000-12-31,E.T. the Extra-Terrestrial,1982,4,0,0,0,...,0,F,12.0,10,48067,ROYAL OAK,MI,42.50,-83.15,US
27,1,1721,4,2000-12-31,Titanic,1997,2,0,0,0,...,0,F,12.0,10,48067,ROYAL OAK,MI,42.50,-83.15,US
31,1,3186,4,2000-12-31,"Girl, Interrupted",1999,1,0,0,0,...,0,F,12.0,10,48067,ROYAL OAK,MI,42.50,-83.15,US
36,1,1836,5,2000-12-31,"Last Days of Disco, The",1998,1,0,0,0,...,0,F,12.0,10,48067,ROYAL OAK,MI,42.50,-83.15,US
37,1,1022,5,2000-12-31,Cinderella,1950,3,0,0,1,...,0,F,12.0,10,48067,ROYAL OAK,MI,42.50,-83.15,US
38,1,2762,4,2000-12-31,"Sixth Sense, The",1999,1,0,0,0,...,0,F,12.0,10,48067,ROYAL OAK,MI,42.50,-83.15,US
39,1,150,5,2000-12-31,Apollo 13,1995,1,0,0,0,...,0,F,12.0,10,48067,ROYAL OAK,MI,42.50,-83.15,US
41,1,1961,5,2000-12-31,Rain Man,1988,1,0,0,0,...,0,F,12.0,10,48067,ROYAL OAK,MI,42.50,-83.15,US
42,1,1962,4,2000-12-31,Driving Miss Daisy,1989,1,0,0,0,...,0,F,12.0,10,48067,ROYAL OAK,MI,42.50,-83.15,US
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
452179,6040,3703,4,2000-07-29,Mad Max 2 (a.k.a. The Road Warrior),1981,2,1,0,0,...,0,M,29.5,6,11106,ASTORIA,NY,40.78,-73.91,US
452221,6040,1077,5,2000-07-29,Sleeper,1973,2,0,0,0,...,0,M,29.5,6,11106,ASTORIA,NY,40.78,-73.91,US
452326,6040,373,4,2000-07-29,Red Rock West,1992,1,0,0,0,...,0,M,29.5,6,11106,ASTORIA,NY,40.78,-73.91,US
452333,6040,1900,5,2000-07-29,"Children of Heaven, The (Bacheha-Ye Aseman)",1997,1,0,0,0,...,0,M,29.5,6,11106,ASTORIA,NY,40.78,-73.91,US
452336,6040,535,4,2000-07-29,Short Cuts,1993,1,0,0,0,...,0,M,29.5,6,11106,ASTORIA,NY,40.78,-73.91,US
452343,6040,1273,4,2000-07-29,Down by Law,1986,2,0,0,0,...,0,M,29.5,6,11106,ASTORIA,NY,40.78,-73.91,US
452354,6040,495,2,2000-07-29,In the Realm of the Senses (Ai no corrida),1976,1,0,0,0,...,0,M,29.5,6,11106,ASTORIA,NY,40.78,-73.91,US
452205,6040,3182,5,2001-03-10,Mr. Death: The Rise and Fall of Fred A. Leucht...,1999,1,0,0,0,...,0,M,29.5,6,11106,ASTORIA,NY,40.78,-73.91,US
452025,6040,1270,3,2001-08-10,Back to the Future,1985,2,0,0,0,...,0,M,29.5,6,11106,ASTORIA,NY,40.78,-73.91,US
452064,6040,2571,4,2001-08-10,"Matrix, The",1999,3,1,0,0,...,0,M,29.5,6,11106,ASTORIA,NY,40.78,-73.91,US
452071,6040,457,4,2001-08-10,"Fugitive, The",1993,2,1,0,0,...,0,M,29.5,6,11106,ASTORIA,NY,40.78,-73.91,US
452077,6040,1784,3,2001-08-10,As Good As It Gets,1997,2,0,0,0,...,0,M,29.5,6,11106,ASTORIA,NY,40.78,-73.91,US
452081,6040,3421,3,2001-08-10,Animal House,1978,1,0,0,0,...,0,M,29.5,6,11106,ASTORIA,NY,40.78,-73.91,US
452089,6040,3671,4,2001-08-10,Blazing Saddles,1974,2,0,0,0,...,1,M,29.5,6,11106,ASTORIA,NY,40.78,-73.91,US
452115,6040,1921,4,2001-08-10,Pi,1998,2,0,0,0,...,0,M,29.5,6,11106,ASTORIA,NY,40.78,-73.91,US
452116,6040,2725,4,2001-08-10,Twin Falls Idaho,1999,1,0,0,0,...,0,M,29.5,6,11106,ASTORIA,NY,40.78,-73.91,US
452142,6040,1947,4,2001-08-10,West Side Story,1961,2,0,0,0,...,0,M,29.5,6,11106,ASTORIA,NY,40.78,-73.91,US
452150,6040,161,3,2001-08-10,Crimson Tide,1995,3,0,0,0,...,0,M,29.5,6,11106,ASTORIA,NY,40.78,-73.91,US
452154,6040,1673,4,2001-08-10,Boogie Nights,1997,1,0,0,0,...,0,M,29.5,6,11106,ASTORIA,NY,40.78,-73.91,US
452183,6040,953,5,2001-08-10,It's a Wonderful Life,1946,1,0,0,0,...,0,M,29.5,6,11106,ASTORIA,NY,40.78,-73.91,US
452206,6040,3362,4,2001-08-10,Dog Day Afternoon,1975,3,0,0,0,...,0,M,29.5,6,11106,ASTORIA,NY,40.78,-73.91,US
452225,6040,232,5,2001-08-10,Eat Drink Man Woman,1994,2,0,0,0,...,0,M,29.5,6,11106,ASTORIA,NY,40.78,-73.91,US
452237,6040,1258,4,2001-08-10,"Shining, The",1980,1,0,0,0,...,0,M,29.5,6,11106,ASTORIA,NY,40.78,-73.91,US
452260,6040,2917,4,2001-08-10,Body Heat,1981,2,0,0,0,...,0,M,29.5,6,11106,ASTORIA,NY,40.78,-73.91,US
452264,6040,1212,5,2001-08-10,"Third Man, The",1949,2,0,0,0,...,0,M,29.5,6,11106,ASTORIA,NY,40.78,-73.91,US
452286,6040,1333,4,2001-08-10,"Birds, The",1963,1,0,0,0,...,0,M,29.5,6,11106,ASTORIA,NY,40.78,-73.91,US
452297,6040,2575,4,2001-08-10,"Dreamlife of Angels, The (La Vie rêvée des ang...",1998,1,0,0,0,...,0,M,29.5,6,11106,ASTORIA,NY,40.78,-73.91,US
452314,6040,1211,5,2001-08-10,Wings of Desire (Der Himmel über Berlin),1987,3,0,0,0,...,0,M,29.5,6,11106,ASTORIA,NY,40.78,-73.91,US
452344,6040,2068,4,2001-08-10,Fanny and Alexander,1982,1,0,0,0,...,0,M,29.5,6,11106,ASTORIA,NY,40.78,-73.91,US
452147,6040,1221,4,2001-08-20,"Godfather: Part II, The",1974,3,1,0,0,...,0,M,29.5,6,11106,ASTORIA,NY,40.78,-73.91,US

In [49]:
urm.isnull().sum()

userID             0
movieID            0
rating             0
time               0
title              0
year               0
howManyGenres      0
Action             0
Adventure          0
Animation          0
Children's         0
Comedy             0
Crime              0
Documentary        0
Drama              0
Fantasy            0
Film-Noir          0
Horror             0
Musical            0
Mystery            0
Romance            0
Sci-Fi             0
Thriller           0
War                0
Western            0
gender             0
age                0
occupation         0
zipCode            0
city               0
state              0
lat              820
long             820
country            0
dtype: int64